### ISSUE TITLE
Error while running with a different dataset

### ISSUE THREAD

**Issue by peeyushgupta** [smcql/smcql#5]
I used a dataset with a single table partitioned into two parts with most of the columns as protected with each site having around 1000 rows.

Database schema (test_schema.sql) 
```
DROP TABLE IF EXISTS INI_TABLE;
CREATE TABLE INI_TABLE (
  TID integer NOT NULL,
  L_ORDERKEY integer NOT NULL,
  L_PARTKEY integer NOT NULL,
  L_SUPPKEY integer NOT NULL,
  L_LINENUMBER integer NOT NULL,
);

-- set up security level of attributes
-- default setting: attribute is private
CREATE ROLE public_attribute;
CREATE ROLE protected_attribute;
GRANT SELECT(L_ORDERKEY) ON INI_TABLE TO protected_attribute;
GRANT SELECT(L_PARTKEY) ON INI_TABLE TO protected_attribute;
GRANT SELECT(L_SUPPKEY) ON INI_TABLE TO protected_attribute;
GRANT SELECT(L_LINENUMBER) ON INI_TABLE TO protected_attribute;
```

The query I run is 
```
SELECT COUNT(DISTINCT l_orderkey) as ok_cnt FROM ini_table d where l_linenumber=6
```
The code gives following error 
```
$ ./build_and_execute.sh conf/workload/sql/tpc.sql testDB1 testDB2 
Creating executable...
Executing Query...

Query:
SELECT COUNT(DISTINCT l_orderkey) as ok_cnt
FROM ini_table d where l_linenumber=6
[testDB2] java.lang.ArrayIndexOutOfBoundsException: 64
[testDB2] 	at com.oblivm.backend.circuits.arithmetic.IntegerLib.eq(IntegerLib.java:353)
[testDB2] 	at org.smcql.generated.userQuery.Distinct4.NoClass.run(NoClass.java:141)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
[testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Evaluator.secureCompute(SMCQLRunnable.java:256)
[testDB2] 	at com.oblivm.backend.util.EvaRunnable.runCore(EvaRunnable.java:57)
[testDB2] 	at com.oblivm.backend.util.EvaRunnable.run(EvaRunnable.java:78)
[testDB2] 	at java.lang.Thread.run(Thread.java:748)
[testDB1] java.lang.ArrayIndexOutOfBoundsException: 64
[testDB1] 	at com.oblivm.backend.circuits.arithmetic.IntegerLib.eq(IntegerLib.java:353)
[testDB1] 	at org.smcql.generated.userQuery.Distinct4.NoClass.run(NoClass.java:141)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
[testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Generator.secureCompute(SMCQLRunnable.java:83)
[testDB1] 	at com.oblivm.backend.util.GenRunnable.runCore(GenRunnable.java:54)
[testDB1] 	at com.oblivm.backend.util.GenRunnable.run(GenRunnable.java:77)
[testDB1] 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by Aqua-Dream** [comment]
I also cannot run my own queries. The errors may vary according to different queries, but none of them show what was wrong.
``` bash
Exception in thread "main" java.lang.NullPointerException
        at org.smcql.util.CodeGenUtils.getBitmask(CodeGenUtils.java:182)
        at org.smcql.util.CodeGenUtils.getBitmask(CodeGenUtils.java:202)
        at org.smcql.type.SecureRelRecordType.getBitmask(SecureRelRecordType.java:179)
        at org.smcql.codegen.smc.operator.support.RexNodeToSmc.visitInputRef(RexNodeToSmc.java:22)
        at org.smcql.codegen.smc.operator.support.RexNodeToSmc.visitInputRef(RexNodeToSmc.java:6)
        at org.apache.calcite.rex.RexInputRef.accept(RexInputRef.java:112)
        at org.smcql.codegen.smc.operator.support.RexFlattener.getSmcString(RexFlattener.java:100)
        at org.smcql.codegen.smc.operator.support.RexFlattener.visitCall(RexFlattener.java:140)
        at org.smcql.codegen.smc.operator.support.RexFlattener.visitCall(RexFlattener.java:24)
        at org.apache.calcite.rex.RexCall.accept(RexCall.java:108)
        at org.smcql.codegen.smc.operator.support.RexNodeUtilities.flattenForSmc(RexNodeUtilities.java:53)
        at org.smcql.codegen.smc.operator.support.RexNodeUtilities.flattenFilter(RexNodeUtilities.java:44)
        at org.smcql.codegen.smc.operator.SecureOperator.handleFilters(SecureOperator.java:138)
        at org.smcql.codegen.smc.operator.SecureOperator.baseVariables(SecureOperator.java:180)
        at org.smcql.codegen.smc.operator.SecureJoin.generate(SecureJoin.java:38)
        at org.smcql.codegen.smc.operator.SecureOperator.compileIt(SecureOperator.java:255)
        at org.smcql.codegen.QueryCompiler.generateSecureStep(QueryCompiler.java:387)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:286)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.<init>(QueryCompiler.java:134)
        at org.smcql.runner.SMCQLRunner.main(SMCQLRunner.java:38)
```
when the query is
``` sql
select
        l_orderkey,
        sum(l_extendedprice * (1 - l_discount)) as revenue
from
        customer as c,
        orders as o,
        lineitem as l
where
        c.c_custkey = o.o_custkey
        and l.l_orderkey = o.o_orderkey
group by
        l_orderkey
limit 10
```

Or 
``` bash
Exception in thread "main" java.lang.NullPointerException
        at org.smcql.codegen.sql.SqlGenerator.getStringFromNode(SqlGenerator.java:35)
        at org.smcql.codegen.sql.SqlGenerator.getSourceSql(SqlGenerator.java:27)
        at org.smcql.codegen.plaintext.PlainOperator.generate(PlainOperator.java:69)
        at org.smcql.executor.step.PlaintextStep.generate(PlaintextStep.java:65)
        at org.smcql.executor.step.PlaintextStep.<init>(PlaintextStep.java:40)
        at org.smcql.codegen.QueryCompiler.generatePlaintextStep(QueryCompiler.java:309)
        at org.smcql.codegen.QueryCompiler.generatePlaintextStep(QueryCompiler.java:335)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:262)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.<init>(QueryCompiler.java:134)
        at org.smcql.runner.SMCQLRunner.main(SMCQLRunner.java:38)
```
when the query is
``` sql
select
        l_orderkey,
        sum(l_extendedprice * (1 - l_discount)) as revenue,
        o_orderdate,
        o_shippriority
from
        customer,
        orders,
        lineitem
where
        c_mktsegment = 'AUTOMOBILE'
        and c_custkey = o_custkey
        and l_orderkey = o_orderkey
        and o_orderdate < date '1995-03-13'
        and l_shipdate > date '1995-03-13'
group by
        l_orderkey,
        o_orderdate,
        o_shippriority
order by
        revenue desc,
        o_orderdate
limit 10
```

Or 
``` bash
Exception in thread "main" java.lang.RuntimeException: Bits doesn't match! 64-0 192-128
        at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:344)
        at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
        at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:58)
        at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:207)
        at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
        at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:109)
        at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:219)
        at com.oblivm.compiler.frontend.BitInferenceEngine.process(BitInferenceEngine.java:76)
        at com.oblivm.compiler.frontend.FrontendCompiler.translate(FrontendCompiler.java:190)
        at com.oblivm.compiler.frontend.FrontendCompiler.compile(FrontendCompiler.java:177)
        at com.oblivm.compiler.cmd.Cmd.compile(Cmd.java:38)
        at org.smcql.codegen.smc.DynamicCompiler.compileOblivLang(DynamicCompiler.java:221)
        at org.smcql.codegen.smc.operator.SecureOperator.compileIt(SecureOperator.java:258)
        at org.smcql.codegen.QueryCompiler.generateSecureStep(QueryCompiler.java:387)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:286)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
        at org.smcql.codegen.QueryCompiler.<init>(QueryCompiler.java:134)
        at org.smcql.runner.SMCQLRunner.main(SMCQLRunner.java:38)
````
when the query is
``` sql
select
 l_orderkey,
 sum(l_extendedprice * (1 - l_discount)) as revenue,
 o_orderdate,
 o_shippriority
from
 lineitem l join orders o on l.l_orderkey=o.o_orderkey join customer c on c.c_custkey=o.o_custkey
group by
 l_orderkey,
 o_orderdate,
 o_shippriority
limit 10
```

**Comment by AstraHoo** [comment]
when I run aspirin-count.sql,it also gives following error
```
[smcql-master]# ./build_and_execute.sh conf/workload/sql/aspirin-count.sql testDB1 testDB2
Creating executable...
Executing Query...


Query:
SELECT COUNT(DISTINCT d.patient_id) as rx_cnt
FROM mi_cohort_diagnoses d JOIN mi_cohort_medications m ON d.patient_id = m.patient_id 
WHERE lower(m.medication) like '%aspirin%' AND d.icd9 like '414%' AND d.timestamp_ <= m.timestamp_
Exception in thread "main" java.lang.RuntimeException: Bits doesn't match! 1088-1024	704-448
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:344)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
	at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:58)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:270)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
	at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:60)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:272)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
	at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:60)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:207)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:61)
	at com.oblivm.compiler.ast.DefaultStatementExpressionVisitor.visit(DefaultStatementExpressionVisitor.java:109)
	at com.oblivm.compiler.frontend.BitInferenceEngine.visit(BitInferenceEngine.java:219)
	at com.oblivm.compiler.frontend.BitInferenceEngine.process(BitInferenceEngine.java:76)
	at com.oblivm.compiler.frontend.FrontendCompiler.translate(FrontendCompiler.java:190)
	at com.oblivm.compiler.frontend.FrontendCompiler.compile(FrontendCompiler.java:177)
	at com.oblivm.compiler.cmd.Cmd.compile(Cmd.java:38)
	at org.smcql.codegen.smc.DynamicCompiler.compileOblivLang(DynamicCompiler.java:221)
	at org.smcql.codegen.smc.operator.SecureOperator.compileIt(SecureOperator.java:258)
	at org.smcql.codegen.QueryCompiler.generateSecureStep(QueryCompiler.java:387)
	at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:286)
	at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:271)
	at org.smcql.codegen.QueryCompiler.addOperator(QueryCompiler.java:264)
	at org.smcql.codegen.QueryCompiler.<init>(QueryCompiler.java:134)
	at org.smcql.runner.SMCQLRunner.main(SMCQLRunner.java:38)
```

**Comment by Junzhou-712** [comment]
> I used a dataset with a single table partitioned into two parts with most of the columns as protected with each site having around 1000 rows.
> 
> Database schema (test_schema.sql)
> 
> ```
> DROP TABLE IF EXISTS INI_TABLE;
> CREATE TABLE INI_TABLE (
>   TID integer NOT NULL,
>   L_ORDERKEY integer NOT NULL,
>   L_PARTKEY integer NOT NULL,
>   L_SUPPKEY integer NOT NULL,
>   L_LINENUMBER integer NOT NULL,
> );
> 
> -- set up security level of attributes
> -- default setting: attribute is private
> CREATE ROLE public_attribute;
> CREATE ROLE protected_attribute;
> GRANT SELECT(L_ORDERKEY) ON INI_TABLE TO protected_attribute;
> GRANT SELECT(L_PARTKEY) ON INI_TABLE TO protected_attribute;
> GRANT SELECT(L_SUPPKEY) ON INI_TABLE TO protected_attribute;
> GRANT SELECT(L_LINENUMBER) ON INI_TABLE TO protected_attribute;
> ```
> 
> The query I run is
> 
> ```
> SELECT COUNT(DISTINCT l_orderkey) as ok_cnt FROM ini_table d where l_linenumber=6
> ```
> 
> The code gives following error
> 
> ```
> $ ./build_and_execute.sh conf/workload/sql/tpc.sql testDB1 testDB2 
> Creating executable...
> Executing Query...
> 
> Query:
> SELECT COUNT(DISTINCT l_orderkey) as ok_cnt
> FROM ini_table d where l_linenumber=6
> [testDB2] java.lang.ArrayIndexOutOfBoundsException: 64
> [testDB2] 	at com.oblivm.backend.circuits.arithmetic.IntegerLib.eq(IntegerLib.java:353)
> [testDB2] 	at org.smcql.generated.userQuery.Distinct4.NoClass.run(NoClass.java:141)
> [testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
> [testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
> [testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
> [testDB2] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Evaluator.secureCompute(SMCQLRunnable.java:256)
> [testDB2] 	at com.oblivm.backend.util.EvaRunnable.runCore(EvaRunnable.java:57)
> [testDB2] 	at com.oblivm.backend.util.EvaRunnable.run(EvaRunnable.java:78)
> [testDB2] 	at java.lang.Thread.run(Thread.java:748)
> [testDB1] java.lang.ArrayIndexOutOfBoundsException: 64
> [testDB1] 	at com.oblivm.backend.circuits.arithmetic.IntegerLib.eq(IntegerLib.java:353)
> [testDB1] 	at org.smcql.generated.userQuery.Distinct4.NoClass.run(NoClass.java:141)
> [testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:197)
> [testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.runOne(SMCQLRunnableImpl.java:168)
> [testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnableImpl.secureCompute(SMCQLRunnableImpl.java:101)
> [testDB1] 	at org.smcql.executor.smc.runnable.SMCQLRunnable$Generator.secureCompute(SMCQLRunnable.java:83)
> [testDB1] 	at com.oblivm.backend.util.GenRunnable.runCore(GenRunnable.java:54)
> [testDB1] 	at com.oblivm.backend.util.GenRunnable.run(GenRunnable.java:77)
> [testDB1] 	at java.lang.Thread.run(Thread.java:748)
> ```

The problem happened because the parser of smcql does not support where clause, which means you need to preprocess data before you execute smcql.
